ALTER TABLE profiles ADD COLUMN IF NOT EXISTS avatar_id TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS x_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS telegram_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS website_url TEXT;
